{% set name = "tar" %}
{% set version = "1.33" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://ftp.gnu.org/gnu/{{ name }}/{{ name }}-{{ version }}.tar.xz
  sha256: 66a8344b1dc83a411d311bd1547e0176e56cc311f28ee94a30f84dafb3d9067e

build:
  number: 1
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - make
    - pkg-config
    - gnuconfig
  host:
    - libiconv
test:
  commands:
    - tar --version | grep {{ version }}

about:
  home: https://www.gnu.org/software/tar/
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: 'GNU tape archive program'

  description: |
    GNU tar saves many files together into a single tape or disk
    archive, and can restore individual files from the archive.  It includes
    multivolume support, the ability to archive sparse files, automatic archive
    compression/decompression, remote archives and special features that allow
    tar to be used for incremental and full backups.

extra:
  recipe-maintainers:
    - notestaff
    - xhochy
