{% set name = "tar" %}
{% set version = "1.33" %}
{% set sha256 = "66a8344b1dc83a411d311bd1547e0176e56cc311f28ee94a30f84dafb3d9067e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: http://ftp.gnu.org/gnu/{{ name }}/{{ name }}-{{ version }}.tar.xz
  sha256: {{ sha256 }}

build:
  number: 0
  script: mkdir -p $PREFIX/lib && FORCE_UNSAFE_CONFIGURE=1 ./configure --prefix=$PREFIX && make && make check && make install && make installcheck
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - xz
    - make
    - binutils
    - coreutils
    - pkg-config
test:
  requires:
    - make
    - binutils
    - coreutils
    - bzip2
    - xz
    - lzip
    - lzop
  commands:
    - tar --version | grep {{ version }}

about:
  home: https://www.gnu.org/software/tar/
  license: GPLv3
  license_family: GPL
  license_file: COPYING
  summary: GNU tape archive program

  description: |
    GNU tar saves many files together into a single tape or disk
    archive, and can restore individual files from the archive.  It includes
    multivolume support, the ability to archive sparse files, automatic archive
    compression/decompression, remote archives and special features that allow
    tar to be used for incremental and full backups.

extra:
  recipe-maintainers:
    - notestaff
