{% set name = "tar" %}
{% set version = "1.31" %}
{% set sha256 = "b471be6cb68fd13c4878297d856aebd50551646f4e3074906b1a74549c40d5a2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: http://ftp.gnu.org/gnu/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: FORCE_UNSAFE_CONFIGURE=1 ./configure --prefix=$PREFIX && make && make check && make install
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
  host:

test:
  commands:
    - tar --version | grep {{ version }}

about:
  home: https://www.gnu.org/software/tar/
  license: GPLv3
  license_family: GPL
  license_file: COPYING
  summary: 'GNU tape archive program'

  # The remaining entries in this section are optional, but recommended
  description: |
    GNU tar saves many files together into a single tape or disk
    archive, and can restore individual files from the archive.  It includes
    multivolume support, the ability to archive sparse files, automatic archive
    compression/decompression, remote archives and special features that allow
    tar to be used for incremental and full backups.

extra:
  recipe-maintainers:
    - notestaff
