{% set name = "tar" %}
{% set version = "1.32" %}
{% set sha256 = "d0d3ae07f103323be809bc3eac0dcc386d52c5262499fe05511ac4788af1fdd8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: http://ftp.gnu.org/gnu/{{ name }}/{{ name }}-{{ version }}.tar.xz
  sha256: {{ sha256 }}

build:
  number: 0
  script: mkdir -p $PREFIX/lib && FORCE_UNSAFE_CONFIGURE=1 ./configure --prefix=$PREFIX && make && make check && make install
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - xz
    - make
    - binutils
    - coreutils
    - pkg-config
test:
  requires:
    - make
    - binutils
    - coreutils
  commands:
    - tar --version | grep {{ version }}

about:
  home: https://www.gnu.org/software/tar/
  license: GPLv3
  license_family: GPL
  license_file: COPYING
  summary: 'GNU tape archive program'

  description: |
    GNU tar saves many files together into a single tape or disk
    archive, and can restore individual files from the archive.  It includes
    multivolume support, the ability to archive sparse files, automatic archive
    compression/decompression, remote archives and special features that allow
    tar to be used for incremental and full backups.

extra:
  recipe-maintainers:
    - notestaff
