# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode9.4


env:
  matrix:
    - CONFIG=osx_c_compilerclang
    - CONFIG=osx_c_compilertoolchain_c

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "NW00KkWoG46LAqXYFiOx/MiF9ZuWAm2OFOdFby1C35QX+6+ZO7nZrmTanryG6yolbU7A3344jghDwd1FBh+2H5C/wTPcBadUvMi4oX4pyCm2w+K6F0+KjurljRXNRRnm0QphwNDj3csNrqa+vFsoJJPBY7wODzhiPbIBJYKrj9DKyA5uXFqQ4+SWQEohIBX+COez/kfU13D1i7xsKmDU0bWq9LLSkAVAlyISzNaMF5p2gas2+a6o+JvXjCfPUFXxWYmx0nexMXatwPhTcYpLjHRLy+BaHSJv4TqwZAVKWl+emZo3jRQce1hrUG2fl8i6Ub6CYS9KVRIRAwYhBUTlcxytCz2N55C2jFs8SjIxnsHvqDR2CmEKf4HzifgJuxZVhkOKkpvW3AD2CBJJaYASK+Cp0QUpQJhOJ68vmo9gVXoorTmqaxk5aOASH5c2EgVmC5YKzQR1NDZUSTMf72H0lgTA4TH8Io0IggwXBaZbSUJYVQ+BZg8LgqeCoM7mrRncaYtC8Sgx1SuY6p/LcTbWNkWNpEcGpnA9CZJVnvQJ2IAxKFE9j4EeTgtPZZGV0FSAZ/ixBQEom9LQQVfihQf3JrJGu9MlYAjt2kgdm06ECLBsfPQ+kdwBep2eda76AJOF2RjUHZDc5VvfT18FhNVS68L9JKpoAdM85+sukz+EWZM="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install -n root -c conda-forge --quiet --yes conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml